name: 功能建议
description: 改进现有功能或提出新功能
labels: [ "feature" ]

body:
  - type: markdown
    attributes:
      value: |
        ## 请补全标题并认真填写下方内容

  - type: textarea
    id: feature_description
    attributes:
      label: 功能建议
      description: 想要改进或者添加的功能
    validations:
      required: true

  - type: textarea
    id: extra_info
    attributes:
      label: 额外信息（可选）
      description: 如：为什么需要这个功能？在什么场景下适用？
